name: Release Please

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions: {}

jobs:
  release-please:
    uses: cccteam/github-workflows/.github/workflows/release-please.yml@4987befcc33b8c6a81741990bb9818d55e7446fe # v6.0.0
    permissions:
      contents: write
      pull-requests: write
    with:
      config-file: release-please-config.json
      manifest-file: .release-please-manifest.json
    secrets:
      RELEASE_PLEASE_APP_ID: ${{ secrets.RELEASE_PLEASE_APP_ID }}
      RELEASE_PLEASE_APP_PEM: ${{ secrets.RELEASE_PLEASE_APP_PEM }}