name: Secret Scanning

permissions:
  contents: read

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened] # these are the defaults - synchronize means 'commits pushed to PR'

jobs:
  trufflehog-secret-scanning:
    uses: cccteam/github-workflows/.github/workflows/secrets-scanning.yml@5be491dfaa55f4e80e42bbef5dbe7ca7027f612f # v6.1.1
    permissions:
      contents: read