name: Secret Scanning

permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened] # these are the defaults - synchronize means 'commits pushed to PR'

jobs:
  trufflehog-secret-scanning:
    uses: cccteam/github-workflows/.github/workflows/secrets-scanning.yml@1ccb2a0d5c48271b34c23abb3821e365019838be # v5.24.0
    permissions:
      contents: read