name: Secret Scanning

permissions:
  contents: read

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened] # these are the defaults - synchronize means 'commits pushed to PR'

jobs:
  trufflehog-secret-scanning:
    uses: cccteam/github-workflows/.github/workflows/secrets-scanning.yml@4987befcc33b8c6a81741990bb9818d55e7446fe # v6.0.0
    permissions:
      contents: read